var firstName = 'Tiffany';
var isCool = true;
var totalPets = 1;
console.log('first name: ', firstName);
console.log('is cool: ', isCool);
console.log('total pets: ', totalPets);
console.log('type of first name: ', typeof firstName);
console.log('type of is cool: ', typeof isCool);
console.log('type of total pets: ', typeof totalPets);
var unknown = null;
console.log('value of unknown: ', unknown);
console.log('type of the value of unknown: ', typeof unknown);
var never;
console.log('value of never: ', never);
console.log('type of the value of never: ', typeof never);
