var width = 12;
var height = 14;
var area = width * height;
console.log('Value of the area:', area);
console.log('Type of the area:', typeof area);
var bill = 50;
var payment = 199;
var change = payment - bill;
console.log('Value of the change:', change);
console.log('Type of change:', typeof change);
var quizzes = 65;
var midterm = 87;
var final = 72;
var grade = (quizzes + midterm + final) / 3;
console.log('Value of the grade:', grade);
console.log('Type of grade:', typeof grade);
var firstName = 'Tiffany';
var lastName = 'Brown';
var fullName = firstName + ' ' + lastName;
console.log('Value of fullName:', fullName);
console.log('Type of fullName:', typeof fullName);
var ph = 5;
var isAcidic = ph < 7;
console.log('Value of the isAcidic:', isAcidic);
console.log('Type of isAcidic:', typeof isAcidic);
var headCount = 10;
var isSparta = headCount === 300;
console.log('Value of isSparta:', isSparta);
console.log('Type of isSparta:', typeof isSparta);
var motto = fullName;
motto += ' is the GOAT';
console.log('Value of motto:', motto);
console.log('Type of motto:', typeof motto);
